# Generated by Django 4.1.6 on 2023-02-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.TextField(blank=True),
        ),
    ]
